name: Release Shopware Version

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag Name'
        required: true
        
jobs:
  
    build-play: 
      name: Release play:${{ github.event.inputs.tagName }}
      runs-on: ubuntu-latest
      continue-on-error: true
      steps:
        - name: Clone Code
          uses: actions/checkout@v2
    
        - name: Install Dependencies
          run: make install
    
        - name: ORCA Generate
          run: make generate -B
    
        - name: Build Image
          run: make build image=play tag=${{ github.event.inputs.tagName }} -B

        - name: Run SVRUnit Tests
          run: make test image=play tag=${{ github.event.inputs.tagName }} -B
          
        - name: Store SVRUnit Report
          uses: actions/upload-artifact@v2
          if: always()
          with:
            name: svrunit_report_play_${{ github.event.inputs.tagName }}
            retention-days: 3
            path: |
                .reports
                
        - name: Start Image
          run: |
            docker run --rm -p 80:80 --name shop -d dockware/play:${{ github.event.inputs.tagName }}
            sleep 30
            docker logs shop

        - name: Install Cypress
          run: cd tests/cypress && make install -B

        - name: Run Cypress Tests
          run: |
            if [[ $DW_IMAGE == flex ]]; then
               cd tests/cypress && make run-flex url=http://localhost
            fi
            if [[ $DW_IMAGE == essentials ]]; then
               cd tests/cypress && make run-essentials url=http://localhost
            fi
            if [[ $DW_IMAGE == play && $SW_VERSION == latest ]]; then
               cd tests/cypress && make run6 url=http://localhost
            fi
            if [[ $DW_IMAGE == dev && $SW_VERSION == latest ]]; then
               cd tests/cypress && make run6 url=http://localhost
            fi
            if [[ $SW_VERSION == 6.* ]]; then
               cd tests/cypress && make run6 url=http://localhost
            fi
            if [[ $SW_VERSION == 5.* ]]; then
               cd tests/cypress && make run5 url=http://localhost
            fi
          env:
            DW_IMAGE: play
            SW_VERSION: ${{ github.event.inputs.tagName }}

        - name: Store Cypress Results
          uses: actions/upload-artifact@v2
          if: always()
          with:
            name: cypress_results_play_${{ github.event.inputs.tagName }}
            retention-days: 1
            path: |
              Tests/Cypress/cypress/videos
              Tests/Cypress/cypress/screenshots     

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
        - name: Push Multi-Arch to Docker Hub
          run: make build-and-push-multiarch image=play tag=${{ github.event.inputs.tagName }} -B
  
    build-dev: 
      name: Release dev:${{ github.event.inputs.tagName }}
      runs-on: ubuntu-latest
      continue-on-error: true
      steps:
        - name: Clone Code
          uses: actions/checkout@v2
    
        - name: Install Dependencies
          run: make install
    
        - name: ORCA Generate
          run: make generate -B
    
        - name: Build Image
          run: make build image=dev tag=${{ github.event.inputs.tagName }} -B

        - name: Run SVRUnit Tests
          run: make test image=dev tag=${{ github.event.inputs.tagName }} -B
          
        - name: Store SVRUnit Report
          uses: actions/upload-artifact@v2
          if: always()
          with:
            name: svrunit_report_dev_${{ github.event.inputs.tagName }}
            retention-days: 3
            path: |
                .reports
                
        - name: Start Image
          run: |
            docker run --rm -p 80:80 --name shop -d dockware/dev:${{ github.event.inputs.tagName }}
            sleep 30
            docker logs shop

        - name: Install Cypress
          run: cd tests/cypress && make install -B

        - name: Run Cypress Tests
          run: |
            if [[ $DW_IMAGE == flex ]]; then
               cd tests/cypress && make run-flex url=http://localhost
            fi
            if [[ $DW_IMAGE == essentials ]]; then
               cd tests/cypress && make run-essentials url=http://localhost
            fi
            if [[ $DW_IMAGE == play && $SW_VERSION == latest ]]; then
               cd tests/cypress && make run6 url=http://localhost
            fi
            if [[ $DW_IMAGE == dev && $SW_VERSION == latest ]]; then
               cd tests/cypress && make run6 url=http://localhost
            fi
            if [[ $SW_VERSION == 6.* ]]; then
               cd tests/cypress && make run6 url=http://localhost
            fi
            if [[ $SW_VERSION == 5.* ]]; then
               cd tests/cypress && make run5 url=http://localhost
            fi
          env:
            DW_IMAGE: dev
            SW_VERSION: ${{ github.event.inputs.tagName }}

        - name: Store Cypress Results
          uses: actions/upload-artifact@v2
          if: always()
          with:
            name: cypress_results_dev_${{ github.event.inputs.tagName }}
            retention-days: 1
            path: |
              Tests/Cypress/cypress/videos
              Tests/Cypress/cypress/screenshots     

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
        - name: Push Multi-Arch to Docker Hub
          run: make build-and-push-multiarch image=dev tag=${{ github.event.inputs.tagName }} -B